Repository TNCT-Mechatech/SerialBridge, pull requests merged in 2021-09, with the labels that each got.

#6 機能の改善と冗長部の削除
  src/CobsSerial.hpp
  src/Message.hpp
  src/source/CobsSerial.cpp
  src/source/SerialBridge.cpp
Labels: Type: improvement

#5 ファイル内ドキュメントの作成
  src/CobsSerial.hpp
  src/InoHardwareSerial.hpp
  src/LinuxHardwareSerial.hpp
  src/MbedHardwareSerial.hpp
  src/Message.hpp
  src/SerialBridge.hpp
  src/SerialDev.hpp
  src/cobs.hpp
  src/source/CobsSerial.cpp
  src/source/LinuxHardwareSerial.cpp
  src/source/Message.cpp
  src/source/SerialBridge.cpp
  src/source/cobs.cpp
Labels: 0: help wanted, Feedback: feature request, Priority: low, Type: documentation

#7 Preprocessor Macroの調査 #4に基づく変更
  src/InoHardwareSerial.hpp
  src/MbedHardwareSerial.hpp
  src/source/InoHardwareSerial.cpp
  src/source/LinuxHardwareSerial.cpp
  src/source/MbedHardwareSerial.cpp
Labels: Priority: low, Type: design, Type: documentation

#9 mbed6.0への対応
  src/MbedHardwareSerial.hpp
  src/source/MbedHardwareSerial.cpp
Labels: Priority: high, Problem: bug, Type: improvement

#11 Feature readme v1.0.0 beta
  README.md
Labels: Type: documentation

#12 実装例を追加
  example/arduino/echoback_server/TestMsg.h
  example/arduino/echoback_server/echoback_server.ino
  example/arduino/helloworld/helloworld.ino
  example/linux/echoback_client/TestMsg.h
  example/linux/echoback_client/echoback_client.cpp
  example/linux/helloworld/helloworld.cpp
  example/mbed/echoback_server/TestMsg.h
  example/mbed/echoback_server/echoback_server.cpp
  example/mbed/helloworld/helloworld.cpp
Labels: Type: documentation

#14 Release v1.0.0beta
  LICENSE
  README.md
  example/arduino/echoback_server/TestMsg.h
  example/arduino/echoback_server/echoback_server.ino
  example/arduino/helloworld/helloworld.ino
  example/linux/echoback_client/TestMsg.h
  example/linux/echoback_client/echoback_client.cpp
  example/linux/helloworld/helloworld.cpp
  example/mbed/echoback_server/TestMsg.h
  example/mbed/echoback_server/echoback_server.cpp
  example/mbed/helloworld/helloworld.cpp
  keywords.txt
  library.properties
  makefile
  src/CobsSerial.hpp
  src/InoHardwareSerial.hpp
  src/LinuxHardwareSerial.hpp
  src/MbedHardwareSerial.hpp
  src/Message.hpp
  src/SerialBridge.hpp
  src/SerialDev.hpp
  src/cobs.hpp
  src/source/CobsSerial.cpp
  src/source/InoHardwareSerial.cpp
  src/source/LinuxHardwareSerial.cpp
  src/source/MbedHardwareSerial.cpp
  src/source/Message.cpp
  src/source/SerialBridge.cpp
  src/source/cobs.cpp
Labels: Priority: high, Type: improvement

#16 Messageクラスの改良
  src/Message.hpp
  src/SerialBridge.hpp
  src/source/Message.cpp
  src/source/SerialBridge.cpp
Labels: Type: improvement

#17 バッファサイズを引数から変更できるようにした
  src/CobsSerial.hpp
  src/SerialBridge.hpp
  src/source/CobsSerial.cpp
  src/source/SerialBridge.cpp
Labels: Type: new feature
